- hosts: server
  vars:
    wr_dir: ~/webrecorder
    wr_ratelimit_exclude: []

    wr_app_host: 'test2.webrecorder.io'
    wr_content_host: 'test2.wbrc.io'

    cert_key_name: '{{ wr_app_host }}'

    nginx_conf_template: "{{ playbook_dir }}/templates/nginx.conf"
    nginx_vhost_template: "{{ playbook_dir }}/templates/wrhost.conf"
    nginx_remove_default_vhost: true
    nginx_vhosts:
      - server_name: "{{ wr_app_host }}"
        filename: "{{ wr_app_host }}.conf"
        include_ws: true

      - server_name: "{{ wr_content_host }}"
        filename: "{{ wr_content_host }}.conf"
        include_ws: false

    certbot_email: 'support@webrecorder.io'
    pip_install_packages:
      - name: docker-compose
      - name: cryptography

  roles:
    - { role: geerlingguy.pip, become: true, become_user: root }
    - { role: certbot, become: true, become_user: root }
    - { role: geerlingguy.nginx, become: true, become_user: root }
    - { role: geerlingguy.docker, become: true, become_user: root }
    - { role: wrinit }
#  tasks:

