- hosts: server
  vars:
    wr_dir: ~/webrecorder

    cert_key_name: '{{ wr_app_host }}'

    certbot_email: 'test@example.com'

    nginx_conf_template: "{{ playbook_dir }}/templates/nginx.conf"
    nginx_vhost_template: "{{ playbook_dir }}/templates/wrhost.conf"
    nginx_remove_default_vhost: true

    nginx_ppa_use: true
    nginx_ppa_version: stable

    nginx_vhosts:
      - server_name: "{{ wr_app_host }}"
        filename: "{{ wr_app_host }}.conf"
        include_ws: true

      - server_name: "{{ wr_content_host }}"
        filename: "{{ wr_content_host }}.conf"
        include_ws: false

    pip_install_packages:
      - name: docker-compose

  pre_tasks:
    - fail:
        msg: 'Variables "wr_app_host" and "wr_content_host" must be defined'
      when: "'wr_app_host' not in vars or 'wr_content_host' not in vars"

  roles:
    - { role: geerlingguy.pip, become: true, become_user: root }
    - { role: certbot, become: true, become_user: root, when: 'wr_app_host != "localhost"' }
    - { role: geerlingguy.nginx, become: true, become_user: root }
    - { role: geerlingguy.docker, become: true, become_user: root }
    - { role: webrecorder_init }
#  tasks:

