  - name: 'WR Clone'
    git:
      repo: 'https://github.com/webrecorder/webrecorder'
      dest: '{{ wr_dir }}'

  - stat: 'path={{ wr_dir }}/wr.env'
    register: wr_env

  - name: 'WR Init'
    shell: ./init-default.sh
    args:
      chdir: '{{ wr_dir }}'
    when: wr_env.stat.exists == False

  - name: 'WR Run Docker Compose'
    become: true
    become_user: "{{ ansible_user_id }}"
    docker_service:
      project_src: '{{ wr_dir }}'
      build: yes
      state: present   

