---
  - name: 'Install Certbot'
    include_role:
      name: geerlingguy.certbot

  - block:
      - include: run.yml

    rescue:
      - name: 'Stop nginx'
        service: name=nginx state=stopped

      - include: run.yml


