---
  - name: Run Certbot
    command: certbot certonly --staging --standalone --expand --agree-tos --email "{{ certbot_email }}" --no-redirect -n -d "{{ wr_app_host }},{{ wr_content_host }}"
    register: runcert

  - debug: var=runcert


